#!/usr/bin/env python

import click

from src.commands import train
from src.commands import test


@click.group()
def cli():
    pass

cli.add_command(train)
cli.add_command(test)


if __name__ == '__main__':
    try:
        cli()
    except KeyboardInterrupt:
        pass
